language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t snsiddh/docker-react -f Dockerfile.dev .

script:
  - docker run snsiddh/docker-reach npm run test -- --coverage  
